name       : pyflakes
version    : 2.3.1
release    : 13
source     :
    - https://github.com/PyCQA/pyflakes/archive/refs/tags/2.3.1.tar.gz : e412510ec082c5c1ba9c68b16603041446b3f5302026636b7697394b3c0d901e
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    passive checker of Python programs
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python3_test
    %python_test
