name       : pyflakes
version    : 2.0.0
release    : 5
source     :
    - https://github.com/PyCQA/pyflakes/archive/2.0.0.tar.gz : 5be24a8f586555e1bc2ff4e566fbad1f59f702d5d88a9b8838b0d0cb7217fa4f
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    passive checker of Python programs
builddeps  :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python3_test
    %python_test
