name       : pyflakes
version    : 1.5.0
release    : 1
source     :
    - https://pypi.python.org/packages/5b/b7/dcd6ebc826065ca4ccd2406aac4378e1df6eb91124625d45d520219932a1/pyflakes-1.5.0.tar.gz : aa0d4dff45c0cc2214ba158d29280f8fa1129f3e87858ef825930845146337f4
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    passive checker of Python programs
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
check      : |
    # Fakeroot borks the tests
    unset LD_PRELOAD
    python setup.py test
