name       : pyflakes
version    : 2.5.0
release    : 16
source     :
    - https://github.com/PyCQA/pyflakes/archive/refs/tags/2.5.0.tar.gz : 0b71a63ab57f5cc9c4a3032460b850da86af8afc63b1888f77527d98b5323a37
homepage   : https://github.com/PyCQA/pyflakes
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    A simple program which checks Python source files for errors. Pyflakes analyzes programs and detects various errors. It works by parsing the source file, not importing it, so it is safe to use on modules with side effects. It's also much faster.
build      : |
    %python3_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
check      : |
    %python3_test
