name       : pyflakes
version    : 3.0.1
release    : 17
source     :
    - https://github.com/PyCQA/pyflakes/archive/refs/tags/3.0.1.tar.gz : 524bdeacfb69c7ca27a544f8fd7b49ead8ab3fca2cf35fca9f0360e2f836636b
homepage   : https://github.com/PyCQA/pyflakes
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    A simple program which checks Python source files for errors. Pyflakes analyzes programs and detects various errors. It works by parsing the source file, not importing it, so it is safe to use on modules with side effects. It's also much faster.
build      : |
    %python3_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
check      : |
    %python3_test
