name       : pyflakes
version    : 1.5.0
release    : 4
source     :
    - https://github.com/PyCQA/pyflakes/archive/1.5.0.tar.gz : 943ba426420a66b5adebdbe8007e676bba11bf4006e7964d9d9ae98478c57792
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    passive checker of Python programs
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
