name       : pyflakes
version    : 2.1.1
release    : 9
source     :
    - https://github.com/PyCQA/pyflakes/archive/2.1.1.tar.gz : 2c98f07a9dd57d9f33561f6b54a64a766cdf79a3c869bd8c07b7fe03094fb8c3
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    passive checker of Python programs
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python3_test
    %python_test
