name       : pyflakes
version    : 2.4.0
release    : 15
source     :
    - https://github.com/PyCQA/pyflakes/archive/refs/tags/2.4.0.tar.gz : 9803cd88f3538566535fc3cf76ad68e90bc5fc5c8434ef8181fb49eec39617f2
homepage   : https://github.com/PyCQA/pyflakes
license    : MIT
component  : programming.python
summary    : Passive checker of Python programs
description: |
    A simple program which checks Python source files for errors. Pyflakes analyzes programs and detects various errors. It works by parsing the source file, not importing it, so it is safe to use on modules with side effects. It's also much faster.
builddeps  :
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |
    %python3_test
    %python_test
